### ISSUE TITLE
[Question] mvn -Dcucumber.options="--help" test on skeleton does not work?

### ISSUE THREAD

**Issue by cmavromichalis** [cucumber/cucumber-java-skeleton#13]
Hello,

I checked out the cucumber-java-skeleton looking for a working example of -Dcucumber.options=""; if I run 'mvn -Dcucumber.options="--help" test' it will not print the help message like the documentation says. It runs the tests and seems to ignore the -Dcucumber.options setting.

Is this a problem with the skeleton project? Documentation? Does there need to be further set up to get this working? 

I am having lots of issues with -Dcucumber.options option; it doesn't seem to be respected. I have been finding a way to get it to work all day.

I am able to run the tests otherwise with mvn test. 

Thank you,
Constantine

**Comment by aslakhellesoy** [comment]
Please use the [support channels](https://cucumber.io/support) for questions.

This is a bug tracker.

**Comment by cmavromichalis** [comment]
I will ask there, thanks!
