### ISSUE TITLE
This is no longer the "simplest possible setup for Cucumber-JVM using Java."

### ISSUE THREAD

**Issue by RobAltena** [cucumber/cucumber-java-skeleton#14]
By using:
@CucumberOptions(plugin = {"pretty"})  in RunCukesTest.java we are moving away from simplest.

consequence 1: (relatively innocent)
import cucumber.api.CucumberOptions;   in RuncukesTest.java

consequence 2: (this is the reason for raising an issue)
pom.xml , the entire build section can be removed.

As I am new to github, I am raising an issue and not submitting a pull request. Happy to discuss here first and create the pull request later if we decide to simplify the simplest setup.

Thank you.

**Comment by mpkorstanje** [comment]
Noted. We'll keep both for convenience reasons though.

`@CucumberOptions` is often the next thing people will use so it is good to retain it.

Maven defaults to java 1.6 which prevents the use of lots of some of the nicer language features people would expect to be available.
