### ISSUE TITLE
funny characters on console output of eclipse

### ISSUE THREAD

**Issue by gpapat26** [cucumber/cucumber-java-skeleton#18]
Hello, can you please help ?
I get funny characters  when I run through eclipse : 

  Scenario: Admin user creates Event and Selections                                 [90m# skeleton/admin.feature:3[0m
    [32mGiven [0m[32mmy browser is "[0m[32m[1mfirefox[0m[32m"[0m                                                   [90m# Stepdefs.my_browser_is(String)[0m
    [32mWhen [0m[32mI log to "[0m[32m[1mAdmin[0m[32m" app with username "[0m[32m[1mAdministrator[0m[32m" and password "[0m[32m[1m1ncharge[0m[32m"[0m [90m# Stepdefs.i_log_to_app_with_username_and_password(String,String,String)[0m
    [32mThen [0m[32mI should be able to create a "[0m[32m[1mPre-Play[0m[32m" Event with its selections[0m          [90m# Stepdefs.i_should_be_able_to_create_a_Event_with_its_selections(String)[0m

1 Scenarios ([32m1 passed[0m)
3 Steps ([32m3 passed[0m)
0m23.421s

But when I run through console : mvn test its all fine.

**Comment by ham1** [comment]
Those are the ANSI control sequences to colour the text, not sure how to solve it in eclipse though, https://marketplace.eclipse.org/content/ansi-escape-console might help?

**Comment by gpapat26** [comment]
thanks :)

**Comment by anjaliyadav02** [comment]
Thanks :)
It works.

**Comment by Arun2784** [comment]
> Those are the ANSI control sequences to colour the text, not sure how to solve it in eclipse though, https://marketplace.eclipse.org/content/ansi-escape-console might help?

It works even after 4 years of your reply

**Comment by kanjanrajesh** [comment]
> Those are the ANSI control sequences to colour the text, not sure how to solve it in eclipse though, https://marketplace.eclipse.org/content/ansi-escape-console might help?

Works even after 5 years of your reply :)
