### ISSUE TITLE
Call your package anything you want, except 'cucumber'

### ISSUE THREAD

**Issue by themathmagician** [cucumber/cucumber-java-skeleton#19]
I think it is worth mentioning in the docs, that the step definitions package should not be called cucumber, as this gives failed tests.

**Comment by aslakhellesoy** [comment]
Can you paste the failure here please?

**Comment by tjkemper** [comment]
I think this [Gist](https://gist.github.com/tjkemper/ac5e96e105a4be55ad5f2bd5cdf71ee1) is related.

**Comment by mpkorstanje** [comment]
It appears to be entirely unrelated.
