### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: gherkin/formatter/Formatter

### ISSUE THREAD

**Issue by mike-vogel** [cucumber/cucumber-java-skeleton#20]
Download
Import into eclipse
Run feature as cucumber 
fails with exception: Exception in thread "main" java.lang.NoClassDefFoundError: gherkin/formatter/Formatter

I didn't touch the pom or anything else after importing.

"mvn test" from the command line also fails with the same error

**Comment by mike-vogel** [comment]
mvn dependency:purge-local-repository
and things worked.

**Comment by wilsoncampusano** [comment]
great. I didn't know you are able to clean your local repository like that. good to know.
