### ISSUE TITLE
download and run gradle build fail 

### ISSUE THREAD

**Issue by 8dspaces** [cucumber/cucumber-java-skeleton#23]
step 1. download the package and extract 

step 2. run gradle build 
[...java/cucumber-java-skeleton]$ gradle build

> Task :test

skeleton.RunCukesTest > initializationError FAILED
    java.lang.ExceptionInInitializerError
        Caused by: cucumber.runtime.CucumberException

1 test completed, 1 failed

i am new for cucumber and java, how should i make the skeleton work

**Comment by mlvandijk** [comment]
Hi @8dspaces - 
According to the README, you should use `gradlew test` command (I don't use Gradle myself, so am not too familiar. If you happen to also have Maven, I can help you with that :))

For questions, please join us on Slack: https://cucumberbdd-slack-invite.herokuapp.com/

**Comment by 8dspaces** [comment]
Thanks @mlvandijk 

tried more on the skeleton 

download zip directly 
- mvn test  Fail 
- ./gradlew test Fail 

Clone the Repo
-  mvn test **Pass** 
- ./gradlew test Fail 

hope someone can check and fix it if it can be reproduce 

anyway, i will use the solution that can pass 
thanks for your checking

**Comment by mlvandijk** [comment]
Hi @8dspaces -
Thanks for the update! I'll give it a try with Gradle myself and see if I can figure it out ;)
Glad you have a version that works for now!

**Comment by mlvandijk** [comment]
Update: Am getting the same build results with maven (build success) and gradle (build failed) in my cloned project. However, the cucumber output is the same for both:
```
1 Scenarios (1 undefined)
3 Steps (2 undefined, 1 passed)
```
This is because only the first step is defined; the other two are pending. It appears that Maven interprets this as Build Success while Gradle interprets it as Build Failure. 
I'd have to look into this more, as I'm not too familiar with Gradle. My working assumption is that you should be able to use either (as you'll implement the tests before incorporating into your build process).

**Comment by mpkorstanje** [comment]
There is a subtle difference between the maven and gradle outputs. 

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> One or more feature files failed to parse. See error output above
```

It tries to parse a feature file. Running with `--debug --stacktrace` shows there is another plugin involved that tries to run cucumber directly rather then through JUnit.

```
23:01:43.390 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: org.gradle.api.GradleException: One or more feature files failed to parse. See error output above
23:01:43.390 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.commercehub.gradle.cucumber.CucumberRunner.run(CucumberRunner.groovy:98)
23:01:43.390 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.commercehub.gradle.cucumber.CucumberRunner$run.call(Unknown Source)
23:01:43.390 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.commercehub.gradle.cucumber.CucumberTask.runTests(CucumberTask.groovy:40)
23:01:43.390 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
23:01:43.390 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:136)
23:01:43.390 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:129)
23:01:43.390 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:118)
23:01:43.390 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:623)
23:01:43.390 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:606)
23:01:43.390 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
23:01:43.390 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
```

I reckon removing `com.commercehub.cucumber-jvm` and related config from gradle would solve this problem.
