### ISSUE TITLE
different branches for gradle / maven?

### ISSUE THREAD

**Issue by mattwynne** [cucumber/cucumber-java-skeleton#32]
For someone using maven. the gradle stuff looks like clutter. Could we keep them in separate branches? Or have sub-folders within the one repo for different typical setups? Keeping them both in one repo seems confusing.

**Comment by aslakhellesoy** [comment]
I think having several branches would make it hard to discover, as people usually just get the master branch.

Most java developers have heard about both Maven and Gradle, and even though they might only be familiar with one of them, I don't think many would feel confused or overwhelmed by the presence of two sets of build scripts.

I think we have more to lose than gain from separating them.

**Comment by mlvandijk** [comment]
Agreed with @aslakhellesoy; closing this issue.
