### ISSUE TITLE
Runs fine in gradle; loses step definitions in IntelliJ

### ISSUE THREAD

**Issue by HesterLyons** [cucumber/cucumber-java-skeleton#35]
This project runs perfectly fine when using the command line. When I import it into IntelliJ it loses the step definitions and says they are all undefined (I have added the missing steps to Stepdefs but otherwise have not touched the project).

Any reason this might be?

**Comment by mlvandijk** [comment]
@HesterLyons - How are you running the tests from IntelliJ? Note: You might need to specify the location of the step definitions in the Run Configuration(?)

**Comment by HesterLyons** [comment]
@mlvandijk thank you - weirdly enough it appears IntelliJ was having a strange moment this morning. I have restarted the machine and taken a clean copy of the repo and it now works fine both in IntelliJ and off the command line.

You are right that if the step definitions are held in a different folder that folder should be specified with a 'glue' statement in the cucumberdefinitions. However I think because they are held in the same folder as the RunCucumberTests module they are picked up automatically.

Thank you for the quick reaction!

**Comment by mlvandijk** [comment]
You're welcome. Thank you for the update. Glad you got it to work!

You're right; from the [docs](https://docs.cucumber.io/community/faq/#cucumber-says-my-steps-are-undefined-but-i-have-implemented-step-definitions) on the `Java` tab: "By default Cucumber-JVM will search in the package (or sub-packages) of the runner class."
