### ISSUE TITLE
gradle version does not work

### ISSUE THREAD

**Issue by startext** [cucumber/cucumber-java-skeleton#40]
With maven everything works well - show cucumber tests, suggests missed steps.
With gradle nothing happens.

What helps:
```bash
$ gradle cleanTest test --info
```
or
```bash
$ gradle test --rerun-tasks --info
```

OS: Windows 10
Java: Oracle JDK 1.8.0_221
Gradle: 5.6

Please update documentation.

**Comment by mpkorstanje** [comment]
Fixed. Cheers!
