### ISSUE TITLE
Person class doesn't exist

### ISSUE THREAD

**Issue by MikeEcho** [cucumber/cucumber-java-skeleton#43]
While following the Cucumber School Online tutorial (https://school.cucumber.io/enrollments, "Fundamentals of BDD (Java)"), I was not able to progress past the point where the `Person` class began to be used to model the domain. I searched the repo that I cloned (the latest version), and it appears that class doesn't exist.

**Comment by MikeEcho** [comment]
I have closed this issue because the tutorial goes on to implement `Person` in the next video. The tutorial implied initially that the class should've already been implemented. Confusing.

**Comment by mattwynne** [comment]
Thanks for letting us know @MikeEcho. We're re-doing these videos at the moment and we'll take your feedback into account.
