### ISSUE TITLE
How to disable cucumber message in eclipse

### ISSUE THREAD

**Issue by DThomas221** [cucumber/cucumber-java-skeleton#55]
How to disable this message

![cumcuber1](https://user-images.githubusercontent.com/74933140/100018476-25610800-2da2-11eb-831c-7dc32e5f8fe4.JPG)

Please show me in screenshots or what steps to take??

Thank You

**Comment by mpkorstanje** [comment]
As it says in the message. Add the `cucumber.publish.quite=true` property to a file named `cucumber.properties` in the root of your test resources directory.
