### ISSUE TITLE
Failed gradle test task from the skeleton project.

### ISSUE THREAD

**Issue by zpalazov** [cucumber/cucumber-java-skeleton#75]
### 👓 What did you see?
Failed Gradle test task for the skeleton project.

The test task fails every time on a fresh cloned project.

### ✅ What did you expect to see?
Successful execution of the test task. 

### 📦 Which tool/library version are you using?

The Gradle wrapper from the skeleton project.
Run on Ubuntu 20.04.5 LTS
### 🔬 How could we reproduce it?
1. I cloned the project
2. After I run the test task as suggested in the documentation the output result is a failure. `./gradlew test --rerun-tasks --info
`
3. `RunCucumberTest > Cucumber > Belly > io.cucumber.skeleton.RunCucumberTest.Belly - a few cukes FAILED
    io.cucumber.junit.platform.engine.UndefinedStepException: The step 'I wait 1 hour' and 1 other step(s) are undefined.
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by mpkorstanje** [comment]
Works as expected. 

https://github.com/cucumber/cucumber-java-skeleton/blob/89050489d812d76a19741ba202e702bb68ab898a/README.md?plain=1#L3-L8

It's even tested.

https://github.com/cucumber/cucumber-java-skeleton/blob/89050489d812d76a19741ba202e702bb68ab898a/.github/workflows/build.yml#L31-L35

:smile:

**Comment by zpalazov** [comment]
./gradlew test

> Task :test FAILED

RunCucumberTest > Cucumber > Belly > io.cucumber.skeleton.RunCucumberTest.Belly - a few cukes FAILED
    io.cucumber.junit.platform.engine.UndefinedStepException at TestCaseResultObserver.java:69

1 test completed, 1 failed

FAILURE: Build failed with an exception.

**Comment by mpkorstanje** [comment]
To clarify, the failure is expected. If you were to implement the missing steps, you'd get a passing project.

**Comment by zpalazov** [comment]
Thanks for your time and the clarifivation.
